name: Github actions deployment

on:
  workflow_run:
    workflows: ["Github actions validations"]
    branches: [master]
    types:
      - completed

jobs:
  deployment:
    name: Deployment production
    uses: alexis-gss/github-workflows/.github/workflows/deployment.yml@master
