name: Github actions validations

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened

jobs:
  Stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: NPM depedencies
        run: npm i
      - name: Stylelint validation
        run: npm run stylelint

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: NPM depedencies
        run: npm i
      - name: Eslint validation
        run: npm run eslint

  Phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Setup composer
        uses: php-actions/composer@v6
      - name: Phpstan validation
        run: php vendor/bin/phpstan analyse

  Phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Setup composer
        uses: php-actions/composer@v6
      - name: Phpcs validation
        run: php vendor/bin/phpcs
