name: Github actions validations

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened

jobs:
  Stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: NPM depedencies
        run: npm i
      - name: Stylelint validation
        run: npm run stylelint

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: NPM depedencies
        run: npm i
      - name: Eslint validation
        run: npm run eslint

  Phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Setup composer
        uses: php-actions/composer@v6
      - name: Phpcs validation
        run: php vendor/bin/phpcs

  Phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Setup composer
        uses: php-actions/composer@v6
      - name: Phpstan validation
        run: php vendor/bin/phpstan analyse

  Tests:
    runs-on: ubuntu-latest
    needs: ['Stylelint', 'Eslint', 'Phpcs', 'Phpstan']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: pdo_sqlite, sqlite3
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Setup composer
      uses: php-actions/composer@v6
    - name: Run Preamble
      run: |
        mkdir -p database
        touch database/migrations/database.sqlite
        touch .env
        echo APP_ENV=testing >> .env
        echo APP_KEY=${{ secrets.APP_KEY }} >> .env
        echo DB_CONNECTION=sqlite >> .env
        php artisan migrate --database=sqlite
        mkdir -p build/coverage
    - name: Run tests
      run: php artisan test
